spring:
  profiles:
    active: dev

---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: spring-cloud-config-eureka
#  eureka配置
eureka:
  instance:
    hostname: eureka7001.com #服务端主机的名字，可以为主机的ip
  client:
    register-with-eureka: false #是否向注册中心注册自己，由于是服务端，所以不需要注册自己
    fetch-registry: false #false表示自己是注册中心
    service-url: #监控的页面，url是注册服务的地址，访问就是localhost:7001，不需要其他的后缀,集群就写需要关联的，逗号分割
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/ # 默认的是：http://localhost:8761/eureka/

---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: spring-cloud-config-eureka
#  eureka配置
eureka:
  instance:
    hostname: eureka7001.com #服务端主机的名字，可以为主机的ip
  client:
    register-with-eureka: false #是否向注册中心注册自己，由于是服务端，所以不需要注册自己
    fetch-registry: false #false表示自己是注册中心
    service-url: #监控的页面，url是注册服务的地址，访问就是localhost:7001，不需要其他的后缀,集群就写需要关联的，逗号分割
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7003.com:7003/eureka/ # 默认的是：http://localhost:8761/eureka/
