spring:
  profiles:
    active: dev

---
server:
  port: 8001
mybatis:
  type-aliases-package: edu.ncu.dong.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: dev
  application:
    name: spring-cloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo_db1?useUnicode=ture&serverTimezone=GMT%2B8
    username: root
    password: dl199808
#erueka
eureka:
  client: #服务注册到哪里
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept ip:localhost port:8001
# info配置，实际上也没啥用
info:
  app.name: provider-dept-dev
  company.name: edu.ncu.dongli

---
server:
  port: 8001
mybatis:
  type-aliases-package: edu.ncu.dong.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: test
  application:
    name: spring-cloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_demo_db1?useUnicode=ture&serverTimezone=GMT%2B8
    username: root
    password: dl199808
#erueka
eureka:
  client: #服务注册到哪里
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept ip:localhost port:8001
# info配置，实际上也没啥用
info:
  app.name: provider-dept-test
  company.name: edu.ncu.dongli